"""Add solution_path to competitions

Revision ID: 7ddea8acd12e
Revises: a351d97b3fca
Create Date: 2026-01-25 02:45:39.325111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddea8acd12e'
down_revision: Union[str, None] = 'a351d97b3fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('solution_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'solution_path')
    # ### end Alembic commands ###
