"""Add data_dictionary_entries table and variable_notes field

Revision ID: df24361f7f11
Revises: 9e6eceef8dc8
Create Date: 2026-01-28 00:23:27.792020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df24361f7f11'
down_revision: Union[str, None] = '9e6eceef8dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_dictionary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('encoding', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['competition_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_dictionary_entries_file_id'), 'data_dictionary_entries', ['file_id'], unique=False)
    op.add_column('competition_files', sa.Column('variable_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition_files', 'variable_notes')
    op.drop_index(op.f('ix_data_dictionary_entries_file_id'), table_name='data_dictionary_entries')
    op.drop_table('data_dictionary_entries')
    # ### end Alembic commands ###
